name: Matvey Bank Engine
on:
  workflow_dispatch:
    inputs:
      card:
        description: 'Номер карты'
      amount:
        description: 'Сумма'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bank Script
        run: python bank_engine.py ${{ github.event.inputs.card }} ${{ github.event.inputs.amount }}
      - name: Save Changes
        run: |
          git config --global user.name "MatveyBankBot"
          git config --global user.email "bot@matvey.os"
          git add bank.json
          git commit -m "🏦 Пополнение баланса"
          git push
